// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"context"
	"msps/internal/app/api"
	"msps/internal/app/controller"
	"msps/internal/app/router"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	agent := api.ProvideAgentSet()
	client := api.ProvideClientSet()
	db, err := router.InitDatabase()
	if err != nil {
		return nil, nil, err
	}
	userController := controller.NewUserController(db)
	emailController := controller.NewEmailController(db)
	routerRouter, err := router.NewRouter(agent, client, userController, emailController, db)
	if err != nil {
		return nil, nil, err
	}
	engine := initHttpServer(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, func() {
	}, nil
}
